### ISSUE TITLE
求支持音视频通信

### ISSUE THREAD

**Issue by Layne2016** [FreddyChen/NettyChat#3]

**Comment by FreddyChen** [comment]
> No description provided.

原生的音视频编解码非常复杂，编写代码时间都很长，更何况还要在文章里面讲清楚原理的话，那工作量会非常大。后续有机会的话，我会抽时间尝试一下。

**Comment by chlss** [comment]
用这个库做音视频实时二进制数据传送可以支持吗？

**Comment by monkeyklp** [comment]
> 用这个库做音视频实时二进制数据传送可以支持吗？

应该是支持的

**Comment by FreddyChen** [comment]
> 用这个库做音视频实时二进制数据传送可以支持吗？

支持的
