### ISSUE TITLE
消息发送的问题

### ISSUE THREAD

**Issue by LinkZhang** [FreddyChen/NettyChat#4]
1. 消息长度用2个字节标识，所有消息长度不能大于65535，但是发送消息的时候没有判断消息长度
如果超过长度发消息会报异常，但这条消息还是会重发几次
![image](https://user-images.githubusercontent.com/10371414/56858071-39b30800-69a7-11e9-8062-1bdc526d5f4c.png)
2.重试的间隔写错了吧，应该是getResendInterval()吧
![image](https://user-images.githubusercontent.com/10371414/56858149-34a28880-69a8-11e9-8581-e665794c6218.png)

**Comment by FreddyChen** [comment]
> 1. 消息长度用2个字节标识，所有消息长度不能大于65535，但是发送消息的时候没有判断消息长度
>    如果超过长度发消息会报异常，但这条消息还是会重发几次
>    ![image](https://user-images.githubusercontent.com/10371414/56858071-39b30800-69a7-11e9-8062-1bdc526d5f4c.png)
>    2.重试的间隔写错了吧，应该是getResendInterval()吧
>    ![image](https://user-images.githubusercontent.com/10371414/56858149-34a28880-69a8-11e9-8581-e665794c6218.png)

看了一下，确实是，您真细心，谢谢提醒哈，今天晚上改改把代码重新提交一下。

**Comment by LinkZhang** [comment]
😀最近正好在做IM这块，不过用的是websocket做的，期待您用websocket实现的文章和代码
